In [9]:
from numpy import *
from pandas import *
from myapikey import APIkey
# for jupyter notebook this is nice
%matplotlib inline
# I use a dark theme so I set it to white.
import matplotlib.pyplot as plt
COLOR = 'white'
plt.rcParams['text.color'] = COLOR
plt.rcParams['axes.labelcolor'] = COLOR
plt.rcParams['xtick.color'] = COLOR
plt.rcParams['ytick.color'] = COLOR

from alpha_vantage.timeseries import TimeSeries


In [17]:
ts = TimeSeries(key=APIkey, output_format='pandas')
data, meta_data = ts.get_intraday(symbol='GOOGL', interval='1min', outputsize='full')
ndata = data.to_numpy()
# perhaps clip the data off for today, and predict today? 


In [18]:
print(data)

                       1. open    2. high     3. low   4. close  5. volume
date                                                                      
2019-02-22 09:31:00  1109.1300  1109.3900  1106.8500  1108.5250    37964.0
2019-02-22 09:32:00  1108.5159  1109.6801  1108.5159  1108.5400     7475.0
2019-02-22 09:33:00  1107.2400  1108.0699  1107.2400  1107.3700     6777.0
2019-02-22 09:34:00  1107.4500  1107.4500  1106.0000  1106.0000     7174.0
2019-02-22 09:35:00  1106.0400  1106.4700  1105.3650  1106.3250     7420.0
2019-02-22 09:36:00  1106.2500  1106.2500  1106.2500  1106.2500      801.0
2019-02-22 09:37:00  1105.9500  1107.5350  1105.9500  1107.5350     6506.0
2019-02-22 09:38:00  1108.4799  1108.5400  1105.1500  1105.1500    12425.0
2019-02-22 09:39:00  1105.7029  1105.8600  1105.5100  1105.5100     4351.0
2019-02-22 09:40:00  1105.3700  1105.3700  1104.5000  1104.5000     4511.0
2019-02-22 09:41:00  1104.8700  1105.6801  1104.0699  1104.0699     8260.0
2019-02-22 09:42:00  1104

In [27]:
print(ndata)

[[ 1109.13    1109.39    1106.85    1108.525  37964.    ]
 [ 1108.5159  1109.6801  1108.5159  1108.54    7475.    ]
 [ 1107.24    1108.0699  1107.24    1107.37    6777.    ]
 ...
 [ 1125.66    1125.6895  1124.87    1124.87   12819.    ]
 [ 1125.095   1125.5     1124.99    1125.4725 17868.    ]
 [ 1125.9     1126.64    1125.49    1126.64   48883.    ]]


In [32]:
test = ndata.copy()
for row in test:
    print(row)


[ 1109.13   1109.39   1106.85   1108.525 37964.   ]
[1108.5159 1109.6801 1108.5159 1108.54   7475.    ]
[1107.24   1108.0699 1107.24   1107.37   6777.    ]
[1107.45 1107.45 1106.   1106.   7174.  ]
[1106.04  1106.47  1105.365 1106.325 7420.   ]
[1106.25 1106.25 1106.25 1106.25  801.  ]
[1105.95  1107.535 1105.95  1107.535 6506.   ]
[ 1108.4799  1108.54    1105.15    1105.15   12425.    ]
[1105.7029 1105.86   1105.51   1105.51   4351.    ]
[1105.37 1105.37 1104.5  1104.5  4511.  ]
[1104.87   1105.6801 1104.0699 1104.0699 8260.    ]
[ 1104.04  1104.04  1102.38  1102.38 10050.  ]
[1103.21 1103.66 1103.   1103.   7254.  ]
[ 1102.7   1102.7   1100.71  1102.12 10557.  ]
[1102.22   1102.5601 1102.1    1102.5601 4607.    ]
[1102.545 1103.215 1102.485 1103.215 3685.   ]
[1103.8296 1103.89   1103.66   1103.89   6723.    ]
[1104.7198 1104.7198 1104.7198 1104.7198 1479.    ]
[1104.72 1104.72 1104.2  1104.2  3526.  ]
[1104.12   1104.12   1103.1554 1103.1554 4290.    ]
[1103.64  1103.76  1103.295 11


[1116.4399 1117.05   1116.4399 1117.05   1883.    ]
[1116.97 1116.97 1116.97 1116.97  485.  ]
[1116.66 1116.66 1116.45 1116.45 1202.  ]
[1116.3  1116.52 1116.3  1116.52 1509.  ]
[1116.7  1116.7  1116.53 1116.53  924.  ]
[1116.4  1116.45 1116.29 1116.29 2200.  ]
[1116.4  1116.59 1116.4  1116.59 1341.  ]
[1116.7032 1116.7032 1116.47   1116.47   2213.    ]
[1115.6725 1116.12   1115.6725 1115.8016 3249.    ]
[1115.61 1115.72 1115.05 1115.05 1935.  ]
[1115.   1115.17 1115.   1115.17 1436.  ]
[1115.01 1115.67 1115.01 1115.67 2510.  ]
[1115.89   1115.89   1115.74   1115.8199 2171.    ]
[1116.5601 1116.5601 1116.13   1116.13    744.    ]
[1115.97   1116.2533 1115.97   1116.2533 1637.    ]
[1116.09   1116.09   1115.5699 1115.5699 2028.    ]
[1116.11 1116.11 1116.11 1116.11 1734.  ]
[1116.  1116.4 1116.  1116.4 1880. ]
[1116.24   1116.24   1115.8217 1116.08   5661.    ]
[1115.46 1115.46 1115.46 1115.46 1665.  ]
[1115.2  1116.04 1115.08 1116.04 3988.  ]
[1115.15 1115.99 1115.15 1115.99 2587.  ]



[1117.15 1117.4  1116.8  1117.4  3373.  ]
[1117.17 1117.7  1117.17 1117.7  2449.  ]
[1117.306  1117.4301 1117.306  1117.4301 1796.    ]
[1117.4  1117.4  1117.05 1117.05 1519.  ]
[1116.98   1116.98   1116.9771 1116.9771 1935.    ]
[ 1117.5699  1118.33    1117.5699  1117.91   15729.    ]
[1117.96  1118.235 1117.96  1118.235 2680.   ]
[1118.   1118.   1117.48 1117.48 3683.  ]
[1117.9813 1117.9813 1117.975  1117.975  2840.    ]
[1117.74 1117.74 1117.45 1117.45 2751.  ]
[1117.66   1117.7156 1117.66   1117.7156 1101.    ]
[1117.95 1117.95 1117.95 1117.95  406.  ]
[1118.1 1118.1 1117.9 1117.9 2222. ]
[1117.88 1117.88 1117.88 1117.88  242.  ]
[1118. 1118. 1118. 1118.  443.]
[1117.98  1118.075 1117.98  1118.075 1453.   ]
[1118.24 1118.34 1118.24 1118.34 1286.  ]
[1118.1703 1118.1703 1118.1703 1118.1703 1481.    ]
[1118.1411 1118.1411 1118.1411 1118.1411  942.    ]
[1117.89 1117.89 1117.89 1117.89  229.  ]
[1117.79 1117.79 1117.79 1117.79  960.  ]
[1117.74 1117.74 1117.51 1117.7  2519.  ]
[1117


[1121.8  1122.28 1121.28 1121.59 4615.  ]
[ 1121.735  1122.75   1121.735  1122.26  12833.   ]
[ 1122.25   1122.29   1121.6    1121.875 18214.   ]
[ 1121.96  1122.51  1121.77  1122.51 10418.  ]
[1122.49  1122.84  1122.15  1122.715 9850.   ]
[ 1122.6899  1123.71    1122.46    1122.89   19174.    ]
[ 1118.78  1119.12  1118.78  1119.12 28411.  ]
[1118.955 1120.3   1118.955 1120.3   4756.   ]
[1120.   1121.15 1120.   1121.15 3487.  ]
[1121.46 1121.46 1121.08 1121.08 4067.  ]
[1121.42 1121.42 1121.4  1121.4  3067.  ]
[1121.29 1121.36 1121.29 1121.35 3742.  ]
[1121.1851 1121.1851 1120.83   1120.83   3780.    ]
[1121.5 1121.5 1121.5 1121.5 1761. ]
[1121.3149 1121.3149 1121.     1121.     2001.    ]
[1121.39 1123.17 1121.39 1122.71 8398.  ]
[1121.85 1121.85 1120.95 1120.95 4591.  ]
[1122.5225 1125.1899 1122.5225 1125.1899 9943.    ]
[1125.41   1125.41   1124.9301 1124.9301 4130.    ]
[1124.33 1124.33 1123.8  1123.8  4872.  ]
[1123.355  1124.0699 1123.355  1124.0699 2463.    ]
[1123.9225 1126.2

[1127.52 1127.53 1127.52 1127.53 1103.  ]
[1127.53 1127.53 1127.53 1127.53  695.  ]
[1127.535 1127.535 1127.26  1127.26  5681.   ]
[1127.6 1127.6 1127.6 1127.6 1264. ]
[1127.39 1127.39 1127.39 1127.39  629.  ]
[1127.515 1127.515 1127.515 1127.515  679.   ]
[1127.38 1127.55 1127.38 1127.55 1097.  ]
[1127.24   1127.24   1127.22   1127.2274 2670.    ]
[1127.3101 1127.6    1127.3101 1127.45   2508.    ]
[1127.78 1127.78 1127.78 1127.78  849.  ]
[1127.61 1127.87 1127.61 1127.87  677.  ]
[1127.7    1127.9301 1127.7    1127.9301 2204.    ]
[1128. 1128. 1128. 1128.  232.]
[1128.1    1128.59   1128.1    1128.5699 3187.    ]
[1127.85   1127.85   1127.5601 1127.5601 2055.    ]
[1127.48  1127.48  1126.985 1127.45  1965.   ]
[1127.49 1127.76 1127.49 1127.74 2507.  ]
[1127.17 1127.49 1127.17 1127.49 3553.  ]
[1127.3619 1127.3619 1127.11   1127.28   1694.    ]
[1127.3706 1127.4    1127.3706 1127.4    2084.    ]
[1127.5699 1127.5699 1127.225  1127.225  2551.    ]
[1127. 1127. 1127. 1127.  695.]
[1126.